# Generated by Django 3.2.5 on 2022-07-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryplans', models.CharField(choices=[('VC', 'Viajes Cortos'), ('AMV', 'Anual Multiviaje'), ('LE', 'Larga Estadia')], max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(choices=[('LC', 'Local'), ('EUR', 'Europa'), ('WW', 'Resto del mundo')], max_length=255)),
                ('dates', models.CharField(max_length=255)),
                ('numPax', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=255)),
                ('typeDocument', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula de Extranjeria')], max_length=255)),
                ('numdocument', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
