# Generated by Django 3.2.5 on 2022-07-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cotizador',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador.countryorigin'),
        ),
        migrations.AlterField(
            model_name='cotizador',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador.countrydestination'),
        ),
        migrations.AlterField(
            model_name='cotizador',
            name='typeDocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador.typedocument'),
        ),
    ]
