# Generated by Django 3.2.5 on 2022-07-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_auto_20220719_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cotizador',
            name='categoryplans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador.categoryplan'),
        ),
    ]
